name: GitHub-Relay-Tunnel
on:
  workflow_dispatch: # اجرای دستی با دکمه

jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Install Xray Core
        run: |
          bash <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
          
      - name: Start Relay Tunnel
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: ${{ secrets.PORT }}
          USER_UUID: ${{ secrets.UUID }}
        run: |
          # ساخت کانفیگ رله: ورودی پورت 8080 گیت‌هاب -> خروجی به سرور تو
          cat <<EOF > config.json
          {
            "inbounds": [{
              "port": 8080,
              "protocol": "vless",
              "settings": { "clients": [{ "id": "$USER_UUID" }], "decryption": "none" },
              "streamSettings": { "network": "tcp" }
            }],
            "outbounds": [{
              "protocol": "vless",
              "settings": {
                "vnext": [{
                  "address": "$REMOTE_HOST",
                  "port": $REMOTE_PORT,
                  "users": [{ "id": "$USER_UUID", "encryption": "none" }]
                }]
              },
              "streamSettings": {
                "network": "xhttp",
                "xhttpSettings": { "path": "/" },
                "security": "tls",
                "tlsSettings": { "serverName": "$REMOTE_HOST" }
              }
            }]
          }
          EOF
          
          # اجرای ایکس‌ری در پس‌زمینه
          /usr/local/bin/xray run -config config.json &
          
          # نصب و اجرای ابزار برای باز کردن پورت گیت‌هاب به بیرون
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url tcp://localhost:8080
